google:
    storage:
        bucket-name: wordcount-1234
spring:
    redis:
        database: 0
        host: localhost
        port: 6379
        password: mypass
    cloud:
      gcp:
          project-id: wordcount-297608
    kafka:
        consumer:
            auto-offset-reset: earliest
            group-id: wordcount
messages:
    topic:
        upload-plain-text: upload-plain-text
        upload-url: upload-url
        upload-path: upload-path
        count: count
