google:
    storage:
        bucket-name: wordcount-1234
spring:
    cloud:
      gcp:
          project-id: wordcount-297608
    kafka:
        consumer:
            auto-offset-reset: earliest
            group-id: wordcount
messages:
    topic:
        upload-plain-text: upload-plain-text
        upload-url: upload-url
        upload-path: upload-path
        count: count
