google:
    storage:
        bucket-name: wordcount-1234
spring:
#    data:
#        redis:
#            repositories:
#                enabled: true
    redis:
        database: 0
        host: localhost
        port: 6379
        password: mypass
    cloud:
      gcp:
          project-id: wordcount-297608
    kafka:
        consumer:
            auto-offset-reset: earliest
            group-id: wordcount
messages:
    topic:
        count-plain-text: count-plain-text
        count-url: count-url
        count-path: count-path